;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Frontend.Widget.InstructionScreen",DevComment="")
+GameplayTagList=(Tag="Frontend.Widget.JoinSessionScreen",DevComment="")
+GameplayTagList=(Tag="Frontend.Widget.LobbyScreen",DevComment="")
+GameplayTagList=(Tag="Frontend.WidgetStack.Instruction",DevComment="")
+GameplayTagList=(Tag="Frontend.WidgetStack.JoinSession",DevComment="")
+GameplayTagList=(Tag="Frontend.WidgetStack.Lobby",DevComment="")

